### ISSUE TITLE
Win64, 'ZMQ' not defined or plugin_host crash

### ISSUE THREAD

**Issue by pfitzseb** [quinnj/Sublime-IJulia#32]
Hey there,
when there are some errors I'm encountering when I'm trying to install/tun IJulia in Sublime Text.
Im on 64bit Windows 8.1 here and tried both the x64 and x86 versions of ST3 - with different problems.
ZMQ and IJulia are installed.

x86:
Installation of the PluginManager and the IJulia-Plugin works flawlessly, but when I try to start a new IJulia notebook, following error occurs:

```
OSError: [WinError 193] %1 is not a valid Win32 application
...
NameError: global name 'zmq' is not defined
```

And yes, I have set the path to the libzmq.dll and the kernel.jl and the julia-readline.exe properly.
This error has been mentioned in #26, but not resolved, so I thought I'd ask again.

x64:
Installation of the Plugin Manager works, but the IJulia-Plugin cannot be installed due to a missing .dll (libgcc_s_seh-1.dll).

```
OSError: [WinError 126] The specified module could not be found
```

That was already mentioned in #11 and is no error with Sublime-Julia per se, but with the plugin_host.exe that comes withST3 and I can actually isntall other plugins without plugin_host crashing.
~~I have not clue how to resolve that error - or rather how to get that .dll... it's nowhere to be found  on the Internet and a mingw installation didn't change anything. But then I don't know much about mingw and all that stuff.~~
I have actually found that dll and another one that was missing to (libstdc++-6.dll) in the Julia install dir and copied them into my installation of ST3. But yeah, another error:

```
Starting IJulia backend...
Starting IJulia backend...
Command Executed: D:/Programme/Julia 0.3.0-prerelease/bin/julia-readline.exe  C:/Users/Basti/.julia/IJulia/src/kernel.jl "D:\Programme\SublimeText3\Data\Packages/User/profile-0.json"
Heartbeat didn't get a response
Heartbeat didn't get a response
Heartbeat didn't get a response
Heartbeat didn't get a response
Heartbeat didn't get a response
Kernel died, closing sockets....
Sockets closed...
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted

```

So I'm guessing that the dlls were the wrong version or something, but as I said: I don't know that much about ST, IJulia and all that good stuff, so I'm kinda clueless as how to proceed now. Hope someone can help me a bit. :)

**Comment by wwkong** [comment]
@Varanas and @quinnj: Thanks for the solutions! I've been having the same issues as Varanas and the "moving the .DLL files" trick worked wonders on a fresh installation of Sublime-IJulia, iPython, and Julia (on 64-bit Windows 8, Julia v0.4.0-dev+3622).
