### ISSUE TITLE
***Kernel Died*** OS 10.9.2

### ISSUE THREAD

**Issue by latreuw** [quinnj/Sublime-IJulia#42]
Hi,

I continue to have troubles with the ***Kernel Died*** message.

When I enter the "Open new IJulia Console" command, julia does start up, but then I immediately get the ***Kernel Died*** message.

This seems to make me think that I have set the path for julia itself correctly but there is something wrong with either the kernel path or the zmq path.  A few comments about each:

ZMQ Path: I used the "using ZMQ; ZMQ.zmq" command in julia to locate this path.  One challenge that I encountered is that the libzmq.dylib file is just an alias for a file in the same folder called libzmq.3.dylib .  I tried both names in the zmq path though and neither seemed to work.  

Kernel Path: Another issue that I encountered is that the default kernel path is given as: "~/.julia/v0.3/IJulia/src/kernel.jl"  In my ".julia" folder though, there is no "v0.3" subfolder.  I have tried just removing the "v0.3" part of the path (since there is an IJulia subfolder) but this does not seem to work either.

I have encountered this error using both julia 0.2.1 and julia 0.3.0.  I am using an unregistered version of sublime text 3 (I want to see if I can actually make sublime work for this application before registering).

As mentioned, I am running OS 10.9.2 on my mac.

Any assistance you can provide would be greatly appreciated.

**Comment by cortner** [comment]
For me, on OS X it turned out I was using the wrong Julia executable (there are 2); see [Issue #59](https://github.com/quinnj/Sublime-IJulia/issues/59)

**Comment by quinnj** [comment]
Consolidating issues to #59
