### ISSUE TITLE
Change default working directory of IJulia console

### ISSUE THREAD

**Issue by tomasaschan** [quinnj/Sublime-IJulia#49]
When I open up an IJulia console using the command palette and run `;pwd`, I get `/opt/sublime_text`, which is slightly unpractical.

The _perfect_ behavior, IMO, would be to choose the working directory from the following list, in the following order:
1. The same directory as where the file currently in focus resides
2. The root of the current project (the first included folder, if there are several)
3. The current user's home directory

I have no idea how hard (or easy) these choices would be to implement compared to each-other, but I imagine that at least the last one would be quite trivial in comparison with the others, and it would still be a big improvement on the current behavior.

**Comment by willtownes** [comment]
is there a way to put the `IJulia: Set as working dir` command into a settings file so it defaults to whatever the currently open file is (to avoid having to run the command every time I open a file?
