### ISSUE TITLE
Julia process launches but in terminal window, not in sublime

### ISSUE THREAD

**Issue by rwjackson** [quinnj/Sublime-IJulia#59]
This is the console message I get when trying to open a new sublime window iJulia process:

Writing file /Users/randalljackson/Library/Application Support/Sublime Text 3/Packages/User/Sublime-IJulia.sublime-settings with encoding UTF-8 (atomic)
reloading Packages/User/Sublime-IJulia.sublime-settings
no command for selector: noop:
Starting IJulia backend...
Command Executed: /Applications/Julia-0.3.0.app/Contents/MacOS/Julia  /Users/randalljackson/.Julia/v0.3/IJulia/src/kernel.jl "/Users/randalljackson/Library/Application Support/Sublime Text 3/Packages/User/profile-7.json"
Traceback (most recent call last):
  File "/Users/randalljackson/Library/Application Support/Sublime Text 3/Packages/IJulia/IJulia.py", line 51, in start_kernel
    self.kernel = Kernel.Kernel(self.id,self.cmd,self)
  File "/Users/randalljackson/Library/Application Support/Sublime Text 3/Packages/IJulia/Kernel.py", line 245, in __init__
    self.context = Context()
  File "/Users/randalljackson/Library/Application Support/Sublime Text 3/Packages/IJulia/Kernel.py", line 112, in __init__
    self.ptr = zmq.zmq_ctx_new()
NameError: global name 'zmq' is not defined

**Comment by quinnj** [comment]
Hey everyone, really sorry to not respond sooner, but the past couple months have been crazy with finishing grad school, the holidays, and moving across the country to start a new job. I'm getting settled now, so I'm happy to help troubleshoot if anyone's interested (I understand if not). I even have a Mac now, so hopefully that helps in the troubleshooting phase. Sorry again.

**Comment by cortner** [comment]
Hi - I hope the following is helpful:

I noticed that in all instructions above you write `/Applications/Julia-0.X.X.app/Contents/MacOS/Julia` as the correct path to Julia. In fact, the correct path is 
`/Applications/Julia-0.X.X.app/Contents/Resources/julia/bin/julia`

In my own settings I use
```
"osx": {
    "zmq_shared_library": "/usr/local/Cellar/zeromq/3.2.4/lib/libzmq.dylib",
    "commands": [
        {
            "command_name": "default",
            "julia": "julia",
            "julia_args": "",
            "ijulia_kernel": "~/.julia/v0.3/IJulia/src/kernel.jl"
        }
    ]
},
```
with `/Applications/Julia-0.X.X.app/Contents/Resources/julia/bin/` in the path.

**Comment by quinnj** [comment]
Thanks for the addition @cortner. I also just updated the front page README with some extra tips and instructions, so hopefully that helps. Again, if anyone has specific issues they'd like some help to debug, I'm more than happy to help now. I could do a Google Hangouts or whatever if that's helpful.

**Comment by rwjackson** [comment]
Thanks so much!  The Julia process now launches in Sublime as it should.

**Comment by quinnj** [comment]
Alright! Awesome. I'll close this for now then. If others have issues with the kernel dying, let's move the discussion to #60.

**Comment by Pureti** [comment]
thanks for the help, its working.
Julia-0.X.X.app->   i missed .app earlier.
